train:
  train_dir: "data/processed/train"
  val_dir: "data/processed/valid"
  batch_size: 32
  lr: 0.0001
  num_epochs: 30
  num_classes: 8
  image_size: 224
  model_path: "models/resnet_latest.pth"
  metrics_output: "metrics/train_metrics.json"
  patience: 5
  resume: false
  backbone: resnet18   # change to any model if preferred

evaluate:
  model_path: models/resnet_latest.pth
  test_dir: data/processed/test
  batch_size: 32
  image_size: 224
  metrics_output: metrics/eval_metrics.json